[application]

[web.app]

# HTML title tag content
title = "ak2tp-projekt"
base_path = "/AK2TP_Projekt" #pro lokální testing toto zakomentovat, pro git website odkomentovat


# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
