[application]

[web.app]

# HTML title tag content
title = "ak2tp-projekt"
# base_path = "/AK2TP_Projekt"
#toto bude třeba odkomentovat před finálním commitem na git

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
